org: rgtimothy
app: calioo-restaurant-inventory
service: calioo-restaurant-inventory
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  profile: calioo-restaurant-inventory
  region: us-east-1
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action: 
          - dynamodb:*
      Resource: '*'

custom:
  tableName: inventory

functions:
  getInventory:
    handler: api/getInventory.handler
    events:
      - httpApi:
          path: /inventory
          method: get
      - httpApi:
          path: /inventory/{id}
          method: get
  postInventory:
    handler: api/postInventory.handler
    events:
      - httpApi:
          path: /inventory
          method: post
  putInventory:
    handler: api/putInventory.handler
    events:
      - httpApi:
          path: /inventory-discount
          method: put

resources:
  Resources:
    RestaurantDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: restaurant_id
            AttributeType: S
          - AttributeName: inventory_id
            AttributeType: S
        KeySchema:
          - AttributeName: restaurant_id
            KeyType: HASH
          - AttributeName: inventory_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST